# 欠損値を穴埋めする関数を作成

## 条件

- ある列内のリストを展開し、縦持ちの1行1データのデータフレームに変換
- 列名を指定して処理

## 困りごと

特になし

In [59]:
# from logging import getLogger, StreamHandler, DEBUG
# logger = getLogger(__name__)
# handler = StreamHandler()
# handler.setLevel(DEBUG)
# logger.setLevel(DEBUG)
# logger.addHandler(handler)
# logger.propagate = False

In [58]:
import numpy as np
import pandas as pd

## 1. 入力：データフレームを作成

In [3]:
# 以下のReserveのように横持（リスト）を縦持ちに展開する関数を作成してください

import numpy as np
import pandas as pd
dfm = pd.DataFrame(
    [
    {"Pos":"QB","regular":12,"Reserve":[9,8]},
    {"Pos":"CB","regular":28,"Reserve":[37,23,38,20]},
    {"Pos":"WR","regular":19,"Reserve":[83,82,81,17,18]},
    {"Pos":"T","regular":69,"Reserve":[75,78]},
    {"Pos":"S","regular":36,"Reserve":[35,21,29,27]},
    {"Pos":"RB","regular":22,"Reserve":[33,88,30]}
    ]
     ,columns=["Pos","regular","Reserve"]
)
dfm

  Pos  regular               Reserve
0  QB       12                [9, 8]
1  CB       28      [37, 23, 38, 20]
2  WR       19  [83, 82, 81, 17, 18]
3   T       69              [75, 78]
4   S       36      [35, 21, 29, 27]
5  RB       22          [33, 88, 30]

## 2. 処理：データ型を変えずに穴埋め

In [57]:
# 01_pattern_list_to_vertical.py
dfm = pd.DataFrame(
    [
    {"Pos":"QB","regular":12,"Reserve":[9,8]},
    {"Pos":"CB","regular":28,"Reserve":[37,23,38,20]},
    {"Pos":"WR","regular":19,"Reserve":[83,82,81,17,18]},
    {"Pos":"T","regular":69,"Reserve":[75,78]},
    {"Pos":"S","regular":36,"Reserve":[35,21,29,27]},
    {"Pos":"RB","regular":22,"Reserve":[33,88,30]}
    ]
)

to_vertical_columns = "Reserve"
outname = 'pattern_list_to_vertical.csv'

# DataFrameの入れ物（dfm_vertical）を作成
dfm_vertical = pd.DataFrame(columns=dfm.columns)

# 縦持ち展開したい要素それぞれを抽出
for i in range(len(dfm)):
    # 要素内のリストの各要素を抽出
    for j in range(len(dfm.loc[i, to_vertical_columns])):
        # リストを1要素に変換した行を作成
        dfm_tmp = dfm.loc[i].copy()
        dfm_tmp[to_vertical_columns] = [dfm_tmp.loc[to_vertical_columns][j]]
        # 縦持ち版データフレームに新たに作成した行を追加
        dfm_vertical = dfm_vertical.append(dfm_tmp)
        
        # indexを振り直す
        dfm_vertical = dfm_vertical.reset_index(drop=True)


dfm_vertical

   Pos Reserve regular
0   QB     [9]      12
1   QB     [8]      12
2   CB    [37]      28
3   CB    [23]      28
4   CB    [38]      28
5   CB    [20]      28
6   WR    [83]      19
7   WR    [82]      19
8   WR    [81]      19
9   WR    [17]      19
10  WR    [18]      19
11   T    [75]      69
12   T    [78]      69
13   S    [35]      36
14   S    [21]      36
15   S    [29]      36
16   S    [27]      36
17  RB    [33]      22
18  RB    [88]      22
19  RB    [30]      22

## 3. 出力：各データのデータ型を確認

In [4]:
# 横持（リスト部分だった部分）を縦持に整形する
import numpy as np
import pandas as pd
dfm = pd.DataFrame(
    [
    {"Pos":"QB","regular":12,"Reserve":[9]},
    {"Pos":"QB","regular":12,"Reserve":[8]},
    {"Pos":"CB","regular":28,"Reserve":[37]},
    {"Pos":"CB","regular":28,"Reserve":[23]},
    {"Pos":"CB","regular":28,"Reserve":[38]},
    {"Pos":"CB","regular":28,"Reserve":[20]},
    {"Pos":"WR","regular":19,"Reserve":[83]},
    {"Pos":"WR","regular":19,"Reserve":[82]},
    {"Pos":"WR","regular":19,"Reserve":[81]},
    {"Pos":"WR","regular":19,"Reserve":[17]},
    {"Pos":"T","regular":69,"Reserve":[75]},
    {"Pos":"T","regular":69,"Reserve":[78]},
    {"Pos":"S","regular":36,"Reserve":[35]},
    {"Pos":"S","regular":36,"Reserve":[21]},
    {"Pos":"S","regular":36,"Reserve":[29]},
    {"Pos":"S","regular":36,"Reserve":[27]},
    {"Pos":"RB","regular":22,"Reserve":[33]},
    {"Pos":"RB","regular":22,"Reserve":[88]},
    {"Pos":"RB","regular":22,"Reserve":[30]}
    ]
     ,columns=["Pos","regular","Reserve"]
)
dfm

   Pos  regular Reserve
0   QB       12     [9]
1   QB       12     [8]
2   CB       28    [37]
3   CB       28    [23]
4   CB       28    [38]
5   CB       28    [20]
6   WR       19    [83]
7   WR       19    [82]
8   WR       19    [81]
9   WR       19    [17]
10   T       69    [75]
11   T       69    [78]
12   S       36    [35]
13   S       36    [21]
14   S       36    [29]
15   S       36    [27]
16  RB       22    [33]
17  RB       22    [88]
18  RB       22    [30]

## TODO：関数化・一般化

In [45]:
import numpy as np
import pandas as pd

def pattern_list_to_vertical(dfm, to_vertical_column, outname)
  """
  inputa
    dfm
    to_vertical_columns
  output
    pattern_list_to_vertical.csv
  """
   :
    ここに処理を書く
　：    
  to_csv(outname)

SyntaxError: invalid syntax (<ipython-input-45-cb28ba096aac>, line 4)